DefaultContentLanguage = "en"
"Languages.en.params.aboutSm.description" = ""
"Languages.en.params.aboutSm.title" = ""
"Languages.en.params.hero.btnText" = ""
"Languages.en.params.hero.btnURL" = ""
"Languages.en.params.hero.description" = ""
"Languages.en.params.hero.heading" = ""
"Languages.en.params.hero.photo" = ""
baseURL = "https://www.finerimmigration.com.au/"
defaultContentLanguageInSubdir = false
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
main_photo = ""
pygmentsCodeFences = true
theme = "navigator"
title = "Finer Immigration"
[Languages.en]
dateFormat = "January 2, 2006"
footerAboutTitle = "ENGLISH About"
footerDescription = "ENGLISH Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerQuicklinkTitle = "ENGLISH Quicklinks"
footerServiceTitle = "ENGLISH Service"
footerSubscribeTitle = "ENGLISH Subscribe"
home = "Home"
languageCode = "en-us"
logo = "images/logo.png"
menufixed = false
title = "Work Visa 482 | Finer Immigration Law Firm"
weight = 2
[Languages.en.params.aboutSm]
description = "Australian Visa is not one-size fits-all, it is important that you find the right one for the employee to suit your company structure. You can employ workers who are living overseas but want to come work in Australia by either Sponsoring skilled workers on a permanent basis through the Employer Nomination Scheme or the Regional Sponsored Migration Scheme. You also can sponsoring a worker on a temporary basis through the Temporary Work Skilled subclass 457 visa ( subclass 482) , which allows them to come to Australia to work for up to 4 years. You can also enter into a Labour agreement with the Australian Government. More about the options "
enable = true
title = "Migration Law and Practice in Melbourne "
[Languages.en.params.blog]
enable = true
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
title = "ENGLISH Blog."
topTitle = "OUR UNTOLD STORY"
[Languages.en.params.contact]
address = "1136 Whitehorse Road <br> Box Hill, Australia"
dribbble = "https://dribbble.com/"
enable = true
facebook = "https://www.facebook.com/"
fax = "+61 3827 3590"
instagram = "https://www.instagram.com/"
linkedin = "https://www.linkedin.com/"
mapLatitude = 51.507351
mapLongitude = -0.127758
mapMarker = "images/marker.png"
phone = "(03) 7019 7539"
subtitle = "The first step towards your dream."
title = "Contact Us."
topTitle = "DROP US A NOTE"
twitter = "https://twitter.com/"
[Languages.en.params.cta]
bg = "images/call-to-action/call-to-action-bg-2.jpg"
btnText = "Contact Us"
enable = true
subtitle = "Live and work in Australia. With Finer, life is easier."
title = "The First Step Towards Your Dream"
[Languages.en.params.hero]
btnText = "Contact Us "
btnURL = "/contact/"
button = true
description = "Hello, I am Vivienne  Welcome to our law firm. I, myself a migrant, deeply understand the overwhelming Australian Immigration Procedure. Our law firm is specialising on Australian Employer Sponsored Temporary and Permanent Visas, Visa Refusal Tribunals (Administrative Appeals Tribunal ( AAT)), and Judicial Review (Federal Circuit Court). Our experienced lawyers/migration specialists aim to help valued employees Work & Live in Australia. We are here to help"
enable = true
heading = "Australian Migration & Visas Specialists "
photo = "/images/viv-standing.jpg"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL = "https://www.youtube.com/embed/g3-VxLQO7do"
[[menu.nav]]
name = "Outcomes"
url = "about"
weight = 2
[[menu.nav]]
name = "Contact"
url = "contact"
weight = 4
[[menu.nav]]
name = "Blog"
url = "blog"
weight = 3
[[menu.nav]]
name = "Services"
url = "service"
weight = 1
[[menu.quicklink]]
name = "badges"
url = "about"
weight = 4
[[menu.quicklink]]
name = "faqs"
url = "about"
weight = 3
[[menu.quicklink]]
name = "about"
url = "about"
weight = 2
[[menu.quicklink]]
name = "partners"
url = "about"
weight = 1
[[menu.services]]
name = "graphicdesign"
url = "services"
weight = 1
[[menu.services]]
name = "webdesign"
url = "services"
weight = 2
[[menu.services]]
name = "webdevelopment"
url = "services"
weight = 3
[params]
logo = "images/logo.png"
